/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface Product {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'priceText' : string,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'priceText' : string,
}
export interface QuoteRequest {
  'name' : string,
  'productName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[ProductInput], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'getProductById' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getQuoteRequestsByProduct' : ActorMethod<[string], Array<QuoteRequest>>,
  'submitQuoteRequest' : ActorMethod<[QuoteRequest], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];