/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceText' : IDL.Text,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceText' : IDL.Text,
});
export const Time = IDL.Int;
export const QuoteRequest = IDL.Record({
  'name' : IDL.Text,
  'productName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Category = IDL.Text;

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([ProductInput], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getProductById' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getQuoteRequestsByProduct' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'submitQuoteRequest' : IDL.Func([QuoteRequest], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceText' : IDL.Text,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceText' : IDL.Text,
  });
  const Time = IDL.Int;
  const QuoteRequest = IDL.Record({
    'name' : IDL.Text,
    'productName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Category = IDL.Text;
  
  return IDL.Service({
    'addProduct' : IDL.Func([ProductInput], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getProductById' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getQuoteRequestsByProduct' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'submitQuoteRequest' : IDL.Func([QuoteRequest], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };